### ISSUE TITLE
Issues sending emails

### ISSUE THREAD

**Issue by nathanhornby** [creativedutchmen/email_template_manager#81]
I'm trying to get to the bottom of an issue, hoping you have some insight!

I believe I've set everything up correctly (I've gone through the process many times now!), however I'm struggling to get the emails to send. The log provides me with:

```text
24/02/2015 11:21 > Warning: GenericErrorHandler 2: stream_socket_client() [<a href='function.stream-socket-client'>function.stream-socket-client</a>]: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol on line 505 of file /Users/Nathan/httpdocs/stubbington_ark/symphony/lib/toolkit/class.smtp.php

24/02/2015 11:21 > Warning: GenericErrorHandler 2: stream_socket_client() [<a href='function.stream-socket-client'>function.stream-socket-client</a>]: Failed to enable crypto on line 505 of file /Users/Nathan/httpdocs/stubbington_ark/symphony/lib/toolkit/class.smtp.php

24/02/2015 11:21 > Warning: GenericErrorHandler 2: stream_socket_client() [<a href='function.stream-socket-client'>function.stream-socket-client</a>]: unable to connect to ssl://smtp.gmail.com:587 (Unknown error) on line 505 of file /Users/Nathan/httpdocs/stubbington_ark/symphony/lib/toolkit/class.smtp.php

24/02/2015 11:21 > UNKNOWN: Email Gateway Error (extension_email_template_manager): Unable to open socket. Unknown error
```

I can see that it's not able to connect, however I have a feeling that's due to the other errors surrounding it (the server and port are correct).

Any ideas?

**Comment by nathanhornby** [comment]
Hm, I tried the alternative port, just in case, and am now getting:

24/02/2015 11:31 > Warning: GenericErrorHandler 2: stream_socket_client() [<a href='function.stream-socket-client'>function.stream-socket-client</a>]: unable to connect to ssl://smtp.gmail.com:443 (Operation timed out) on line 505 of file /Users/Nathan/httpdocs/stubbington_ark/symphony/lib/toolkit/class.smtp.php
24/02/2015 11:31 > UNKNOWN: Email Gateway Error (extension_email_template_manager): Unable to open socket. Operation timed out

That one seems like it's definitely an issue at Google's end though.

The error in my OP seems to be this: https://stackoverflow.com/questions/15166950/unable-to-establish-ssl-connection-how-do-i-fix-my-ssl-cert

**Comment by michael-e** [comment]
AFAIK, you can not send to gmail using port 587. If I remember correctly, you must use "SSL" (not TLS) and port 465.

**Comment by nathanhornby** [comment]
Ah, that's contradictory to the instructions they've given me, I'll give that port a try.

**Comment by nathanhornby** [comment]
That did the trick, thanks @michael-e !!

Google sez:

> Outgoing Mail (SMTP) Server - Requires TLS
smtp.gmail.com
Port: 465 or 587
Requires SSL: Yes
Requires authentication: Yes
Use same settings as incoming mail server

It seems only the one port works (the second port I tried was from the paragraph below, for IMAP, so explains why that one simply timed out).

Seems that for whatever reason you can't use port 587.

**Comment by michael-e** [comment]
Normally port 587 is supposed to be used with TLS (which is, somehow, "closer to email standards" than SSL on port 465; anyway…). But I don't know if (or when) they finally make this work. :-)
