### ISSUE TITLE
Multiple receipients

### ISSUE THREAD

**Issue by wdebusschere** [creativedutchmen/email_template_manager#85]
In the emailtemplates we add several comma separated static email addressess, but in the last version of symphony (2.6.4) with the last version of the email_template_manager (7.1.1), only the first one gets the email.. Nothing in the logs.. Got it on multiple sites.. Thx

**Comment by michael-e** [comment]
I can not replicate this issue with Symphony 2.6.3. Do you maybe have any possibility to test on 2.6.3?

**Comment by wdebusschere** [comment]
Symphony 2.6.3 + email_template_manager (7.0) = same problem, only first email gets the mail.

**Comment by michael-e** [comment]
I can not replicate this. Can you provide more information? Have you tried reversing the order to verifiy that it's always the first one? Could it be that some spam filter or email client is fooling you?

**Comment by wdebusschere** [comment]
Michael, i have tried all of this, have it on multiple setups, multiple client emailadresses, what is strange is that my log files (apache and symphony) are empty..

**Comment by michael-e** [comment]
Are the log files written at all?

Have you tried different email settings (different SMTP server, or Sendmail)?

I can only guess… I have no idea what could be causing this.

**Comment by wdebusschere** [comment]
Michael, ok, i will investigate more, is there i line where i could do some debugging. We are using an smtp with auth, worked always perfect. Log files are active.; Will give you more news soon.

**Comment by michael-e** [comment]
For debugging you might try and `var_dump` a bit. :-)

I often use s.th. like the following to dump into a file:

	file_put_contents('/var/www/www.example.com/workspace/debug.txt', var_export($some_variable, TRUE),FILE_APPEND);

I would start in the `_sendEmail` function (extension driver). There you see:

```php
$recipients = array_unique((array) $properties['recipients']);
```

If you dump these, is the array correct?

**Comment by wdebusschere** [comment]
Michael, $recipients is ok, smtp packets are also ok, will need to check with mailserver administrator. Thank you for the debugging info.

**Comment by michael-e** [comment]
Please tell me if you find the issue. Always curious…

**Comment by wdebusschere** [comment]
Michael,

Second recepient is stopped by the spamfilter of the mailserver: Blocked Message quarantined Message was incorrectly formed      
To: =?UTF-8?Q?=00?= <info@XXXXXXX.com>

**Comment by michael-e** [comment]
I can not see where the issue is. Can you please post the complete error formatted as code (by indenting it)?

**Comment by wdebusschere** [comment]
Michael, i don't have more, but will ask, they told me: problem is in the code before the email, its incorrect..
To: =?UTF-8?Q?=00?= info@XXXXXXX.com

**Comment by michael-e** [comment]
Again, can you please post the error **formatted as code block** (by indenting it)?

    a code block will look like this

**Comment by michael-e** [comment]
As far as I can see, there is a NULL character in the recipient's name that shouldn't be there. If you want me to help with this issue, I must know the formatting of your template's recipients string.

**Comment by wdebusschere** [comment]
<code>Received: from mx.mailprotect.be ([178.208.39.142])
 by mxasav001.mailprotect.be with esmtp (Exim 4.85)
 (envelope-from <xxx@xxxxx.be>) id 1aBKXw-0007Hp-Ph
 for info@bananafixe.com; Tue, 22 Dec 2015 11:52:00 +0100
X-Greylist: whitelisted by SQLgrey-1.8.0
Received: from relay-auth172.mailprotect.be (relay-auth172.mailprotect.be
 [77.241.92.172])
 by mx.mailprotect.be (Postfix) with ESMTP id BA3092A03F3
 for <info@destination.com>; Tue, 22 Dec 2015 11:52:00 +0100 (CET)
Received: from [127.0.1.1] (176.62.170.181.static.hosted.by.combell.com
 [176.62.170.181]) (authenticated bits=0)
 by relay-auth.mailprotect.be (8.14.5/8.14.5) with ESMTP id tBMAq0D3004860
 for <info@destination1.com>; Tue, 22 Dec 2015 11:52:00 +0100
Reply-To: =?UTF-8?Q?Firstname_Lastname?= <info@contactformsender.be>
Content-Type: multipart/alternative;
 boundary="=_alt_3ba9453ff8b4f53ff211ca9480ca83eb"
Message-ID: <4972efca20976efe6a3ab31c38014c9b@www.mydomain.be>
Date: Tue, 22 Dec 2015 11:52:00 +0100
From: =?UTF-8?Q?Ecco_La_Luna?= <from@mydomain.be>
Subject: =?UTF-8?Q?ECCO_LA_LUNA_=2D_Contactformulier_E=2Dxperience_Wannes_Debussch?=
 =?UTF-8?Q?ere?=
To: =?UTF-8?Q?=00?= <info@destination.com>
X-Mailer: Symphony Email Module
MIME-Version: 1.0
X-Filter-ID: s0sct1PQhAABKnZB5plbIbXQWJk5hmzVh9K8ImMTooQc6xG4Zdq3xlPzzam3kER/v0WM/M+C7g6f
 jq7KivljIgvPV4jLExytnK40tmdxXmYSoBFXibYCLnxpO/B/zEp9VubZ2ZyA30igafsN9thy3kZU
 uKPMR0C3NE8yfRtRo31cR6vcRlDk/cSBa4A2VcTnkxlSZxHxTWgJwgGAdAfYxxLYjcPsRRMSj/XH
 /7XUtneR62+bT9FLHacdla/UVDLJSmEIS4GON+6FOG36iMWh1KgkAATpsJQGBeS+Pwpc6QI93SsS
 4aMXJmiJ2G0eb5ahFmqLGdV1TXwklRZF1/YRmyIZdrEArEZ2Hyd7pk43GA3DqcigOvSxdRnthmhn
 8Zn6NLSMOBjg5HNH19eQ/O0c3ZhQ/gXVpkQ7m0IC92BT+8DYSBhN39zcwhucNAxDzhVaBfrTvewv
 Y4LRqAXmHYxxqd7rzAXbUWs6ZuSD20nqhWIknYC6ihH/WhxXyOzrpxL7Lz/dsiahQ1DFoGJGH4Qv
 NNWlpDvEmnUrCGcimuwOH6IHuT9lRuiZtFdmSQRp/9wHxyHeXZmsEdacfKykeByeeA==
X-Report-Abuse-To: spam@mxasav001.mailprotect.be
X-Filter-Fingerprint: IFrWXGses7OKB5S5G8/dJR8Z5VD7FZiiT9tK6RAzQuhA3cTUQ1R++keuE7RDJ8Kg3RbMLUalw1oC
 mj99/u+PoqoVy8a3lsStJtAvpObFX0W9pwnCLfzqMQ4SqlQant4mUpndEJ0YoaLytXXo8BMTaX2p
 Mk7LBarWD9Fj4R3eIu6C5spubTEXAEkuBKN3yOZvUxf7JO+oAUByCkP7cAJnEooJtGZFyF6tI/I5
 CWVQH2sjWUvnt4XQmbZjx+Gtm4/p
X-SpamExperts-Class: unknown
X-SpamExperts-Evidence: Badly formed To header.
X-Quarantine-Release-ID: 1aBKXw-0007Hp-Ph-mxasav001.mailprotect.be


--=_alt_3ba9453ff8b4f53ff211ca9480ca83eb
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable</code>

**Comment by michael-e** [comment]
How does your recipients string (in the template) look like?

**Comment by michael-e** [comment]
AFK now, I will be back in some hours.

**Comment by wdebusschere** [comment]
info@email1.com, info@email2.com

info@email1.com receives the mail

**Comment by michael-e** [comment]
I edited your comment. Please use Markdown to format code and code blocks.

So you don't have names, just email addresses separated by commas?

**Comment by wdebusschere** [comment]
Yes

**Comment by michael-e** [comment]
I can not debug this (because it doesn't happen here) without your help.

As a first step, can you repeat the [recipients debugging](https://github.com/creativedutchmen/email_template_manager/issues/85#issuecomment-165477353) and post the recipients array? (I need to see which type of array it is.)

**Comment by wdebusschere** [comment]
'array(2) { [0]=> string(19) "info@bananafixe.com" [1]=> string(19) "info@e-xperience.be" }'

**Comment by michael-e** [comment]
Can you please do the same around 40 lines below that line?

Add the debugging line to the if-clause of this block, and dump `$email->recipients` (after it has been set):

```php
if (General::validateString($emailaddr, $validators['email'])) {
    $email->recipients = array($name => $emailaddr);
} else {
    throw new EmailTemplateException(__("Email address invalid:") . ' ' . $emailaddr);
}
```

Please use `FILE_APPEND`, so we can see all addresses from the loop. Ideally it should look like this (with your path, of course):

```php
if (General::validateString($emailaddr, $validators['email'])) {
    $email->recipients = array($name => $emailaddr);
    file_put_contents('/var/www/www.example.com/workspace/debug.txt', var_export($email->recipients, TRUE),FILE_APPEND);
} else {
    throw new EmailTemplateException(__("Email address invalid:") . ' ' . $emailaddr);
}
```

**Comment by wdebusschere** [comment]
<code>array (
  0 => 'info@bananafixe.com',
)array (
  1 => 'info@e-xperience.be',
)</code>

**Comment by michael-e** [comment]
Perfect.

Good news is bad news in this case: If anything goes wrong from here, it's in the Symphony core.

Which PHP version do you use?

**Comment by michael-e** [comment]
Thinking about it, I have no idea why the second email might fail.

We are sending two emails in a `foreach` loop:

* the first email goes to `array ( 0 => 'info@email1.com', )`
* the second email goes to `array ( 1 => 'info@email2.be', )`

The second email doesn't know anything about the first one, so why chould it behave differently?

@nitriques, @brendo, @creativedutchmen: do you have any ideas?

@wdebusschere: Can you please post the "To" header of the **first** email?

**Comment by wdebusschere** [comment]
<code>X-Mozilla-Keys:                                                                                 
Return-Path: <info@eccolaluna.be>
Delivered-To: info@bananafixe.com
Received: from mxasav001.mailprotect.be (mxasav001.mailprotect.be [178.208.39.180])
	by smtp05.mailprotect.be (Postfix) with ESMTPS id B11DE3C005E
	for <info@bananafixe.com>; Wed, 23 Dec 2015 21:32:12 +0100 (CET)
Received: from mx.mailprotect.be ([178.208.39.142])
	by mxasav001.mailprotect.be with esmtp (Exim 4.85)
	(envelope-from <info@eccolaluna.be>)
	id 1aBq96-0004ex-NM
	for info@bananafixe.com; Wed, 23 Dec 2015 21:36:35 +0100
X-Greylist: whitelisted by SQLgrey-1.8.0
Received: from relay-auth172.mailprotect.be (relay-auth172.mailprotect.be [77.241.92.172])
	by mx.mailprotect.be (Postfix) with ESMTP id A13BC2A0363
	for <info@bananafixe.com>; Wed, 23 Dec 2015 21:36:28 +0100 (CET)
Received: from [192.168.1.3] (178-116-54-108.access.telenet.be [178.116.54.108])
	(authenticated bits=0)
	by relay-auth.mailprotect.be (8.14.5/8.14.5) with ESMTP id tBNKaSbq023745
	for <info@bananafixe.com>; Wed, 23 Dec 2015 21:36:28 +0100
Reply-To: =?UTF-8?Q?Wannes_Debusschere?= <info@e-xperience.be>
Content-Type: multipart/alternative; boundary="=_alt_e057b5a85847aeaded26c1cdcf2727df"
Message-ID: <3e25f082f4001e418e0a5acbf937a272@localhost:8080>
Date: Wed, 23 Dec 2015 21:36:31 +0100
From: =?UTF-8?Q?Ecco_La_Luna?= <info@eccolaluna.be>
Subject: =?UTF-8?Q?ECCO_LA_LUNA_=2D_Contactformulier_E=2Dxperience_Wannes_Debussch?=
 =?UTF-8?Q?ere?=
To: info@bananafixe.com
X-Mailer: Symphony Email Module
MIME-Version: 1.0
X-Filter-ID: s0sct1PQhAABKnZB5plbIUEYE1Gxhf/76k8oVFdf7pgc6xG4Zdq3xlPzzam3kER/v0WM/M+C7g6f
 jq7KivljIgvPV4jLExytnK40tmdxXmYSoBFXibYCLnxpO/B/zEp9VubZ2ZyA30igafsN9thy3kZU
 uKPMR0C3NE8yfRtRo31cR6vcRlDk/cSBa4A2VcTnkxlSZxHxTWgJwgGAdAfYx03NYaeyqg+GMjy3
 k6blSsogWsGmVDiAPkZnyV2ocRSoSmEIS4GON+6FOG36iMWh1KgkAATpsJQGBeS+Pwpc6QI93SsS
 4aMXJmiJ2G0eb5ahFmqLGdV1TXwklRZF1/YRmyIZdrEArEZ2Hyd7pk43GA3DqcigOvSxdRnthmhn
 8Zn6NLSMOBjg5HNH19eQ/O0c3ZhQ/gXVpkQ7m0IC92BT+8DYSBhN39zcwhucNAxDzhVaBfrTvewv
 Y4LRqAXmHYxxqd7rzAXbUWs6ZuSD20nqhWIknYC6ihH/WhxXyOzrpxL7Lz/dsiahQ1DFoGJGH4Qv
 NNWlpDvEmnUrCGcimuwOH6IHuT9lRuiZtFdmSQRp/9wHxyHeXZmsEdacfKykeByeeA==
X-Report-Abuse-To: spam@mxasav001.mailprotect.be
X-Filter-Fingerprint: IFrWXGses7OKB5S5G8/dJR8Z5VD7FZiiT9tK6RAzQuhA3cTUQ1R++keuE7RDJ8Kg3RbMLUalw1oC
 mj99/u+PoqoVy8a3lsStJtAvpObFX0W9pwnCLfzqMQ4SqlQant4mUpndEJ0YoaLytXXo8BMTaX2p
 Mk7LBarWD9Fj4R3eIu6C5spubTEXAEkuBKN3yOZvUxf7JO+oAUByCkP7cAJnEooJtGZFyF6tI/I5
 CWVQH2sjWUvnt4XQmbZjx+Gtm4/p
X-SpamExperts-Class: ham
X-SpamExperts-Evidence: Combined (0.09)
X-Recommended-Action: accept


--=_alt_e057b5a85847aeaded26c1cdcf2727df
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<data>
  <dscontactform1></code>

**Comment by michael-e** [comment]
How bad.

* It looks perfect for the first email: `To: info@bananafixe.com`
* It looks bad for the second email: `To: =?UTF-8?Q?=00?= info@destination.com`

I am lost, I have no idea.

**Comment by michael-e** [comment]
@wdebusschere, can you try to send using a different gateway? (Either switch from SMTP to Sendmail, or use a different SMTP account.) I would like to know if you experience the same issue.

**Comment by nitriques** [comment]
@michael-e I've never used this extension sadly. I've been sending emails using array since quite some times now.

Can somebody change [those lines](https://github.com/creativedutchmen/email_template_manager/blob/5345d9d17ebc9b8c545dc5f23dd9d9c845358ab3/extension.driver.php#L186-L190) with

```php
} catch (Exception $e) {
                        Symphony::Log()->pushToLog(__('Email Template Manager: ') . $e->getMessage(), null, true);
                        //$context['errors'][] = Array('etm-' . $template->getHandle() . '-' . Lang::createHandle($emailaddr), false, $e->getMessage());
                        continue;
                    }
```

To catch all exceptions and log them ?

Also, I would recommend changing from using the direct property names and use the setter/getter especially [here](https://github.com/creativedutchmen/email_template_manager/blob/5345d9d17ebc9b8c545dc5f23dd9d9c845358ab3/extension.driver.php#L178-L182).

**Comment by creativedutchmen** [comment]
> Also, I would recommend changing from using the direct property names and use the setter/getter especially here.

There is no setter for the recipient, for as far as I know. There is a magic `__set()` method, which takes care of validation and calculation (using XPath), so using the property names directly is as designed.

**Comment by nitriques** [comment]
> There is no setter for the recipient, for as far as I know.

Hummm what about [this](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.emailgateway.php#L206)  But yeah I think that [this](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.emailgateway.php#L804-L811) does the trick

**Comment by nitriques** [comment]
But I still feel like ALL exception should be caught...

@wdebusschere What gateway are you using ?

**Comment by creativedutchmen** [comment]
Ah yes, my bad, I was looking in the wrong place. The `Gateway` does indeed have a `setRecipient` method, and it might be cleaner to use that instead. But the setter works, too, so I'm not too concerned;)

**Comment by wdebusschere** [comment]
We use SMTP, can't test with sendmail.

**Comment by nitriques** [comment]
> But the setter works, too, so I'm not too concerned;)

@creativedutchmen we both learn something so I guess that's a win :)

> We use SMTP, can't test with sendmail.

I have the opposite setup and I think I might have found it :) 

Can you try porting [that change](https://github.com/DeuxHuitHuit/symphony-2/commit/51376afe911686122ea659df385a6802943d07ac#diff-e6f175e7374be0eb32974dd6621e0d53R66) on [this line](https://github.com/DeuxHuitHuit/symphony-2/blob/2.6.x/symphony/lib/toolkit/email-gateways/email.smtp.php#L81) 

I have a commit almost ready to go. I am pretty sure it's going to work.

**Comment by wdebusschere** [comment]
Nitriques, yes! It's working now, both comma separeted recipients get the email. Thank you and a happy year!

**Comment by michael-e** [comment]
I have sent a PR with the fix (as proposed by @nitriques) to the Symphony repo.

**Comment by michael-e** [comment]
Ragarding exception handling (and the setter stuff): Please, @creativedutchmen, can you care for this?

**Comment by nitriques** [comment]
> Thank you and a happy year!

@wdebusschere @michael-e @creativedutchmen Happy new year's too!
